
export enum ContactStatus {
  LEAD = 'Lead',
  QUALIFIED = 'Qualified',
  PROPOSAL = 'Proposal',
  ACTIVE = 'Active',
  CLOSED = 'Closed',
}

export interface Note {
  id: string;
  content: string;
  date: string; // ISO string
  author: string;
}

export interface Activity {
  id: string;
  type: 'call' | 'email' | 'meeting' | 'note' | 'upload' | 'proposal' | 'task';
  description: string;
  date: string; // Creation date
  dueDate?: string; // Date for the reminder/follow-up
  isDone?: boolean; // Status of the task
  metadata?: any; 
}

export interface Proposal {
  id: string;
  title: string;
  content: string; // The full proposal text generated by AI
  value: number;
  status: 'Draft' | 'Sent' | 'Accepted' | 'Rejected';
  createdAt: string;
}

export interface Contact {
  id: string;
  // Personal Info
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  
  // Company Info
  company: string;
  siret?: string;
  address?: string;
  industry?: string;

  // CRM Info
  status: string; // Changed from Enum to string to support dynamic pipeline
  tags: string[]; 
  lastContact: string;
  score?: number; // Lead Scoring
  
  // Relationships
  notes: Note[];
  activities: Activity[];
  files: string[]; 
  proposals: Proposal[]; // New: List of commercial offers

  // Consulting specifics
  certificationInterest?: string; 
  contractValue?: number;
}

export interface Toast {
    id: string;
    message: string;
    type: 'success' | 'error' | 'info';
}

// --- Utility: Lead Scoring Algorithm ---
export const calculateScore = (contact: Contact): number => {
    let score = 0;
    
    // Proposals are high value signals
    if (contact.proposals) {
        score += contact.proposals.length * 20;
    }

    // Activity based scoring
    contact.activities.forEach(a => {
        switch (a.type) {
            case 'proposal': score += 10; break; // Activity log for proposal
            case 'meeting': score += 15; break;
            case 'call': score += 10; break;
            case 'email': score += 5; break;
            case 'task': 
                if (a.isDone) score += 5; 
                break;
            case 'note': score += 2; break;
            default: score += 1;
        }
    });

    // Bonus for completed profile
    if (contact.email) score += 5;
    if (contact.phone) score += 5;
    if (contact.siret) score += 5;

    return score;
};

export const getScoreColor = (score: number) => {
    if (score >= 50) return { color: 'text-red-600', bg: 'bg-red-100', icon: '🔥', label: 'Hot' };
    if (score >= 20) return { color: 'text-amber-600', bg: 'bg-amber-100', icon: '⛅', label: 'Warm' };
    return { color: 'text-blue-600', bg: 'bg-blue-100', icon: '❄️', label: 'Cold' };
};
